settings:
  name: HelloWorld.java
  author: 
    - https://github.com/NanowarOfSteel
  image: maven:3.8.8-eclipse-temurin-17

install:
  assertReturnCode: 0
  clone:
  - git clone --depth 1 https://github.com/NanowarOfSteel/HelloWorld.git
  compile:
  - cd HelloWorld/src/main/java/it/nanowar/ofsteel/helloworld; javac HelloWorldMainLauncherClass.java

helloworld:
  assertReturnCode: 1
  assertStdoutContains: 
  - Hello World Programmer Start
  - Hello World!
  - Program Finished!
  assertStderrContains: NullPointerException
  run:
    - cd HelloWorld/src/main/java; java it.nanowar.ofsteel.helloworld.HelloWorldMainLauncherClass
